---
- hosts: 172.31.44.53
  become: yes
  tasks:
  - name: Run the Linux command
    command: hostname -f
    register: resultfor1stresult

  - name: display the result
    debug:
     msg: "{{resultfor1stresult}}"  

  - name: Install git
    apt:
     name: git
     state: present
    when: resultfor1stresult.stderr ==""

  - name: Install tree
    apt: 
     name: tree
     state: present  
     when: resultfor1stresult.stderr !=""
    