---
- hosts: webservers
  become: yes
  tasks:
   - include_tasks: filecontect.yml

   - name: copy the file from Master to node
     copy:
      src: staticfile
      dest: /home/ubuntustatucfile

   - name: Copy the Dynamic file
     template:
      src: index.j2
      dest: /var/www/html/index.html