---
- name: Copy tomcat user xml file in to Node
  template:
   src: template/mytomuser.j2
   dest: /opt/tomcat/conf/tomcat-users.xml

- name: Copy tomcat contest xml file in to Node
  template:
   src: template/mytomcontext.j2
   dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: Copy tomcat host manager xml file in to Node
  template:
   src: template/mytomhost.j2
   dest: //opt/tomcat/webapps/host-manager/META-INF/context.xml   
